include:
  - compose.observability.yml

services:
  web:
    command: >
      opentelemetry-instrument
      --traces_exporter otlp
      --metrics_exporter otlp
      daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/home/verboheit/web
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    depends_on:
      opentelemetry:
        condition: service_started

  db:
    ports:
      - "5432:5432"
    env_file: .env

  redis:
    ports:
      - "6379:6379"

  celery_worker:
    command: >
      opentelemetry-instrument
      --traces_exporter otlp
      --metrics_exporter otlp
      celery -A config worker -l info --events --concurrency=4 --hostname=dev-worker@%h -Q default,emails,comms,scoring,files,reports,cache
    volumes:
      - .:/home/verboheit/web
    env_file: .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    depends_on:
      opentelemetry:
        condition: service_started
  celery_beat:
    command: >
      opentelemetry-instrument
      --traces_exporter otlp
      --metrics_exporter otlp
      celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/home/verboheit/web
    env_file: .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    depends_on:
      opentelemetry:
        condition: service_started

  flower:
    ports:
      - "5555:5555"
    env_file: .env