services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.106.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4318:4318" # OTLP HTTP receiver
      - "9464:9464" # Prometheus metrics exporter
    networks:
      - dev
      - staging
      - prod
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=native-histograms'
      - '--web.enable-remote-write-receiver'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - dev
      - staging
      - prod
    restart: unless-stopped
    depends_on:
      - otel-collector

  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo_data:/var/tempo
    networks:
      - dev
      - staging
      - prod
      
  memcached:
    image: memcached:1.6.38
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m # Set the maximum memory usage
      - MEMCACHED_THREADS=4 # Number of threads to use
    networks:
      - dev
      - staging
      - prod

  tempo:
    image: *tempoImage
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    ports:
      - "3200:3200"
    depends_on:
      - init
      - memcached
    networks:
      - dev
      - staging
      - prod
    restart: unless-stopped
  grafana:
    image: grafana/grafana:11.2.1
    container_name: grafana
    environment:
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
      - GF_PLUGINS_DISABLE_INSTALLATION=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_UPDATE_CHECK_FOR_UPDATES=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - dev
      - staging
      - prod
    restart: unless-stopped
    depends_on:
      - prometheus
      - tempo

volumes:
  prometheus_data:
  tempo_data:
  grafana_data:


networks:
  dev:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_dev
  staging:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_staging
  prod:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_prod