envVarGroups:
  - name: vmlc-secrets

databases:
  # PostgreSQL Database
  - name: vmlc-db
    postgresMajorVersion: 17
    # You can specify a region, e.g., region: oregon

redis:
  # Redis Instance
  - name: vmlc-redis
    redisMajorVersion: 7
    # You can specify a region, e.g., region: oregon

services:
  # Django/Gunicorn Web Service
  - type: web
    name: vmlc-backend
    env: docker
    image:
      repo: theolujay/vmlc-backend
      tag: 0.1.0 # Or specify a specific tag
    dockerCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    healthCheck:
      path: /api/health/
    envVarGroups:
      - vmlc-secrets # Link to the group defined above
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vmlc-db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: vmlc-redis
          property: connectionString

  # Celery Background Worker
  - type: worker
    name: celery-worker
    env: docker
    image:
      repo: theolujay/vmlc-backend
      tag: 0.1.0 # Or specify a specific tag
    dockerCommand: "celery -A config worker -l info"
    envVarGroups:
      - vmlc-secrets # Link to the group defined above
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vmlc-db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: vmlc-redis
          property: connectionString
      - key: C_FORCE_ROOT # Celery-specific variable
        value: "1"