previews:
  generation: automatic

envVarGroups:
  - name: vmlc-secrets

databases:
  - name: vmlc-db
    databaseName: private
    ipAllowList: []

services:
  - name: vmlc-backend
    type: web
    runtime: image
    image:
      url: docker.io/theolujay/vmlc-backend:0.1.0
      creds:
        fromRegistryCreds:
          name: vmlc-creds
    plan: free
    region: frankfurt
    healthCheckPath: /api/v1/health/
    envVars:
      - fromGroup: vmlc-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: vmlc-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: vmlc-redis
          property: connectionString

  # Celery Background Worker
  - type: worker
    name: celery-worker
    region: frankfurt
    runtime: image
    image:
      url: docker.io/theolujay/vmlc-backend:0.1.0
      creds:
        fromRegistryCreds:
          name: vmlc-creds
    dockerCommand: "celery -A config worker -l info"
    envVars:
      - fromGroup: vmlc-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: vmlc-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: vmlc-redis
          property: connectionString

  # Flower Dashboard
  - type: web
    name: flower
    region: frankfurt
    runtime: image
    image:
      url: docker.io/theolujay/vmlc-backend:0.1.0
      creds:
        fromRegistryCreds:
          name: vmlc-creds
    dockerCommand: "celery -A config flower --address=0.0.0.0 --port=5555 --basic-auth=${SUPERUSER_EMAIL}:${SUPERUSER_PASSWORD}"
    envVars:
      - fromGroup: vmlc-secrets

  - type: keyvalue
    name: vmlc-redis
    ipAllowList: []
