# Generated by Django 5.2.6 on 2026-01-30 11:55

from django.db import migrations, models

import identity.validators
import vmlc.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PublicMediaStorage(),
                upload_to="profile_pictures/",
                validators=[identity.validators.validate_profile_picture],
            ),
        ),
        migrations.AlterField(
            model_name="userverification",
            name="face_id",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PrivateMediaStorage(),
                upload_to="face_ids/",
                validators=[identity.validators.validate_face_id],
            ),
        ),
        migrations.AlterField(
            model_name="userverification",
            name="id_card",
            field=models.FileField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PrivateMediaStorage(),
                upload_to="id_cards/",
                validators=[identity.validators.validate_id_card_file],
            ),
        ),
        migrations.AlterField(
            model_name="userverification",
            name="verification_document",
            field=models.FileField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PrivateMediaStorage(),
                upload_to="verification_docs/",
                validators=[identity.validators.validate_document_file],
            ),
        ),
    ]
