# Generated by Django 5.2.6 on 2026-02-25 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_alter_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CowrywiseKidProfile",
            fields=[
                ("username", models.CharField(max_length=255, unique=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cowrywise_kid_profile",
                        serialize=False,
                        to="identity.candidate",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
