# Generated by Django 5.2.6 on 2026-02-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_cowrywisekidprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cowrywisekidprofile",
            options={
                "verbose_name": "Cowrywise Kid",
                "verbose_name_plural": "Cowrywise Kids",
            },
        ),
    ]
