# Generated by Django 5.2.4 on 2025-08-01 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Nigerian phone number for SMS notifications and contact",
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format: '+234XXXXXXXXXX' or '0XXXXXXXXXX'",
                        regex="^(\\+234[789][01]\\d{8}|0[789][01]\\d{8})$",
                    )
                ],
            ),
        ),
    ]
