# Generated by Django 5.2.4 on 2025-08-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_candidatescore_date_recorded_and_more"),
        ("api", "0004_candidatescoresnapshot"),
    ]

    operations = []
