# Generated by Django 5.2.4 on 2025-08-03 22:13

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_merge_20250803_1715"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_pending", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_profile_photos/",
                        validators=[api.models.validate_profile_photo],
                    ),
                ),
                (
                    "id_card",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="user_id_cards/",
                        validators=[api.models.validate_id_card_file],
                    ),
                ),
                (
                    "verification_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="user_verification_docs/",
                        validators=[api.models.validate_document_file],
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Verification",
                "verbose_name_plural": "User Verifications",
            },
        ),
        migrations.RemoveIndex(
            model_name="candidate",
            name="api_candida_role_6cab55_idx",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="id_card",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="id_card",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="profile_photo",
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["role"], name="api_candida_role_56e3df_idx"),
        ),
        migrations.AddField(
            model_name="userverification",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
