# Generated by Django 5.2.4 on 2025-07-31 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_staff_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="candidate_profile",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="candidatescore",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scores",
                to="api.exam",
            ),
        ),
        migrations.AlterField(
            model_name="leaderboardsnapshot",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaderboard_snapshots",
                to="api.staff",
            ),
        ),
    ]
