# Generated by Django 5.2.5 on 2025-09-08 07:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("identity", "0002_alter_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateExamResultSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("data", models.JSONField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("screening", "Screening"), ("league", "League")],
                        db_index=True,
                        default="league",
                        max_length=20,
                    ),
                ),
                (
                    "level",  # This will be renamed to "round" in 0040
                    models.PositiveIntegerField(
                        db_index=True,
                        default=1,
                        help_text="Round within the stage (e.g., 1 for League 1, 2 for League 2)",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                (
                    "exam_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("open_duration_hours", models.PositiveIntegerField(default=12)),
                ("countdown_minutes", models.PositiveIntegerField(default=60)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["stage", "level"],  # Return the old index
                        name="vmlc_exam_stage_91a198_idx",
                    ),
                ],
            },
),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("option_a", models.CharField(blank=True, max_length=255)),
                ("option_b", models.CharField(blank=True, max_length=255)),
                ("option_c", models.CharField(blank=True, max_length=255)),
                ("option_d", models.CharField(blank=True, max_length=255)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                            ("D", "Option D"),
                        ],
                        max_length=1,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CandidateExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "date_recorded",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("auto_score", models.BooleanField(db_index=True, default=False)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="vmlc.exam",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="identity.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_recorded"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(blank=True, to="vmlc.question"),
        ),
        migrations.CreateModel(
            name="CandidateAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                            ("D", "Option D"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="vmlc.candidateexamresult",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vmlc.question"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions_created",
                to="identity.staff",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions_updated",
                to="identity.staff",
            ),
        ),
        migrations.AddField(
            model_name="leaderboardsnapshot",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaderboard_snapshots",
                to="identity.staff",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams_created",
                to="identity.staff",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams_updated",
                to="identity.staff",
            ),
        ),
        migrations.AddField(
            model_name="candidateexamresultsnapshot",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_exam_result_snapshots",
                to="identity.staff",
            ),
        ),
        migrations.AddField(
            model_name="candidateexamresult",
            name="score_submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="identity.staff",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateanswer",
            constraint=models.UniqueConstraint(
                fields=("candidate_result", "question"),
                name="unique_answer_per_candidate_result",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidateexamresult",
            unique_together={("candidate", "exam")},
        ),
    ]