# Generated by Django 5.2.6 on 2025-09-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                    ("sponsor", "Sponsor"),
                    ("volunteer", "Volunteer"),
                ],
                db_index=True,
                default="volunteer",
                max_length=20,
            ),
        ),
    ]
