# Generated by Django 5.2.6 on 2025-10-12 21:06

from django.db import migrations, models
import vmlc.models
import vmlc.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0003_rename_profile_photo_to_face_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverification",
            name="face_id",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PublicMediaStorage(),
                upload_to="face_ids/",
                validators=[vmlc.models.validate_face_id],
            ),
        ),
    ]
