# Generated by Django 5.2.5 on 2025-09-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0003_alter_userverification_id_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverification",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
