# Generated by Django 5.2.6 on 2025-10-12 21:32

import identity.validators
import vmlc.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0004_update_face_id_validator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverification",
            name="face_id",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PrivateMediaStorage(),
                upload_to="face_ids/",
                validators=[identity.validators.validate_face_id],
            ),
        ),
    ]
