# Generated by Django 5.2.6 on 2025-10-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0005_alter_userverification_face_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidatescore",
            options={"ordering": ["-recorded_at"]},
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="candidatescore",
            old_name="date_recorded",
            new_name="recorded_at",
        ),
        migrations.RenameField(
            model_name="candidatescore",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="staff",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="userverification",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="userverification",
            old_name="date_updated",
            new_name="updated_at",
        ),
    ]
