# Generated by Django 5.2.6 on 2025-10-22 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0006_alter_candidatescore_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_staff",
                to="vmlc.staff",
            ),
        ),
    ]
