# Generated by Django 5.2.6 on 2025-10-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0007_staff_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="is_active",
        ),
        migrations.AddField(
            model_name="question",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="candidateanswer",
            name="candidate_score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="vmlc.candidatescore",
            ),
        ),
        migrations.AlterField(
            model_name="candidateanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="vmlc.question"
            ),
        ),
    ]
