# Generated by Django 5.2.6 on 2025-10-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0008_remove_question_is_active_question_archived_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidatescore",
            old_name="submitted_by",
            new_name="score_submitted_by",
        ),
    ]
