# Generated by Django 5.2.6 on 2025-10-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0009_rename_submitted_by_candidatescore_score_submitted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(
                blank=True, related_name="exams", to="vmlc.question"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("moderate", "Moderate"), ("hard", "Hard")],
                default="moderate",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="occupation",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
