# Generated by Django 5.2.6 on 2025-10-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0010_alter_exam_questions_alter_question_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
