# Generated by Django 5.2.6 on 2025-10-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0011_alter_exam_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exam",
            old_name="exam_date",
            new_name="scheduled_date",
        ),
    ]
