# Generated by Django 5.2.6 on 2025-10-29 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0012_rename_exam_date_exam_scheduled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardsnapshot",
            name="exam",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboard_snapshots",
                to="vmlc.exam",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leaderboardsnapshot",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="leaderboardsnapshot",
            unique_together={("exam", "created_at")},
        ),
    ]
