# Generated by Django 5.2.6 on 2025-11-01 09:21

import identity.validators
import vmlc.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0013_leaderboardsnapshot_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PublicMediaStorage(),
                upload_to="profile_pictures/",
                validators=[identity.validators.validate_profile_picture],
            ),
        ),
    ]
