# Generated by Django 5.2.6 on 2025-10-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0013_leaderboardsnapshot_exam_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userverification",
            old_name="is_verified",
            new_name="is_approved",
        ),
    ]
