# Generated by Django 5.2.6 on 2025-10-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0013_leaderboardsnapshot_exam_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leaderboardsnapshot",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("ongoing", "Ongoing"),
                    ("concluded", "Concluded"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="leaderboardsnapshot",
            name="exam",
        ),
    ]
