# Generated by Django 5.2.6 on 2025-10-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0014_alter_leaderboardsnapshot_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="status",
        ),
    ]
