# Generated by Django 5.2.6 on 2025-10-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0015_remove_exam_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="level",
            field=models.PositiveIntegerField(
                db_index=True,
                default=1,
                help_text="Level within the stage (e.g., 1 for League 1, 2 for League 2)",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["stage", "level", "is_active"],
                name="vmlc_exam_stage_91a198_idx",
            ),
        ),
    ]
