# Generated by Django 5.2.6 on 2025-10-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0014_rename_is_verified_userverification_is_approved"),
        ("vmlc", "0016_exam_level_exam_vmlc_exam_stage_91a198_idx"),
    ]

    operations = []
