# Generated by Django 5.2.6 on 2025-11-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0014_user_profile_picture"),
        ("vmlc", "0017_merge_20251030_2310"),
    ]

    operations = []
