# Generated by Django 5.2.6 on 2025-11-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0018_merge_20251101_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_candidates",
                to="vmlc.staff",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_staffs",
                to="vmlc.staff",
            ),
        ),
    ]
