# Generated by Django 5.2.6 on 2025-12-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0019_candidate_created_by_alter_staff_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverification",
            name="rejection_reason",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
