# Generated by Django 5.2.6 on 2025-12-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0020_userverification_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverification",
            name="action_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_users",
                to="vmlc.staff",
            ),
        ),
    ]
