# Generated by Django 5.2.6 on 2026-01-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0021_userverification_action_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="current_class",
            field=models.CharField(
                blank=True,
                choices=[("SS1", "SS1"), ("SS2", "SS2"), ("SS3", "SS3")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="school_type",
            field=models.CharField(
                blank=True,
                choices=[("public", "Public"), ("private", "Private")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
