# Generated by Django 5.2.6 on 2026-01-07 14:12

import identity.validators
import vmlc.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0022_candidate_current_class_candidate_school_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="user",
            name="verification_document",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PrivateMediaStorage(),
                upload_to="verfication_documents/",
                validators=[identity.validators.validate_verification_document],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_document_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userverification",
            name="document_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
