# Generated by Django 5.2.6 on 2026-01-07 16:47

import vmlc.models
import vmlc.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0023_remove_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_document",
            field=models.FileField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PrivateMediaStorage(),
                upload_to="verfication_documents/",
                validators=[vmlc.models.validate_verification_document],
            ),
        ),
    ]
