# Generated by Django 5.2.6 on 2026-01-07 17:52

import identity.models
import vmlc.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0024_alter_user_verification_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PublicMediaStorage(),
                upload_to="profile_pictures/",
                validators=[identity.models.validate_profile_picture],
            ),
        ),
    ]
