# Generated by Django 5.2.6 on 2026-01-08 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0025_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreRegUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Nigerian phone number",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+234XXXXXXXXXX' or '0XXXXXXXXXX'",
                                regex="^(\\+234[789][01]\\d{8}|0[789][01]\\d{8})$",
                            )
                        ],
                    ),
                ),
                (
                    "interest_type",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("volunteer", "Volunteer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
