# Generated by Django 5.2.6 on 2026-01-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0026_prereguser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userverification",
            old_name="document_type",
            new_name="verification_document_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verification_document",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verification_document_type",
        ),
    ]
