# Generated by Django 5.2.6 on 2026-01-09 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vmlc",
            "0027_rename_document_type_userverification_verification_document_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Nigerian phone number",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+234XXXXXXXXXX' or '0XXXXXXXXXX'",
                                regex="^(\\+234[789][01]\\d{8}|0[789][01]\\d{8})$",
                            )
                        ],
                    ),
                ),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("sponsorship", "Sponsorship"),
                            ("partnership", "Partnership"),
                            ("media_support", "Media Support"),
                            ("other", "Other Su"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("consent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default="09123456789",
                help_text="Nigerian phone number",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format: '+234XXXXXXXXXX' or '0XXXXXXXXXX'",
                        regex="^(\\+234[789][01]\\d{8}|0[789][01]\\d{8})$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidate",
            name="school_type",
            field=models.CharField(
                blank=True,
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, default="Lagos", max_length=50),
            preserve_default=False,
        ),
    ]
