# Generated by Django 5.2.6 on 2026-01-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0028_supportinquiry_remove_user_phone_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportinquiry",
            name="support_type",
            field=models.CharField(
                choices=[
                    ("sponsorship", "Sponsorship"),
                    ("partnership", "Partnership"),
                    ("media_publiciy", "Media/Publicity"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
