# Generated by Django 5.2.6 on 2026-01-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0029_alter_supportinquiry_support_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prereguser",
            old_name="phone_number",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
