# Generated by Django 5.2.6 on 2026-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0030_rename_phone_number_prereguser_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflag",
            name="auto_off_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
