# Generated by Django 5.2.6 on 2026-01-18 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0031_featureflag_auto_off_date"),
    ]

    operations = [
        # 1. Enable pgcrypto for gen_random_uuid()
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pgcrypto;", reverse_sql=migrations.RunSQL.noop),

        # 2. Add UUID field to Exam
        migrations.AddField(
            model_name='exam',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunSQL(
            "UPDATE vmlc_exam SET uuid = gen_random_uuid();",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='exam',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

        # 3. CandidateScore migration
        migrations.AddField(
            model_name='candidatescore',
            name='exam_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunSQL(
            """
            UPDATE vmlc_candidatescore
            SET exam_uuid = vmlc_exam.uuid
            FROM vmlc_exam
            WHERE vmlc_candidatescore.exam_id = vmlc_exam.id;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),

        # 4. M2M migration (vmlc_exam_questions)
        # Note: vmlc_exam_questions is the auto-created table for Exam.questions
        migrations.RunSQL(
            """
            ALTER TABLE vmlc_exam_questions ADD COLUMN exam_uuid uuid;
            UPDATE vmlc_exam_questions
            SET exam_uuid = vmlc_exam.uuid
            FROM vmlc_exam
            WHERE vmlc_exam_questions.exam_id = vmlc_exam.id;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),

        # 5. Handle LeaderboardSnapshot (Safety check via SQL block)
        migrations.RunSQL(
            """
            DO $$ 
            BEGIN 
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vmlc_leaderboardsnapshot' AND column_name='exam_id') THEN
                    ALTER TABLE vmlc_leaderboardsnapshot ADD COLUMN exam_uuid uuid;
                    UPDATE vmlc_leaderboardsnapshot
                    SET exam_uuid = vmlc_exam.uuid
                    FROM vmlc_exam
                    WHERE vmlc_leaderboardsnapshot.exam_id = vmlc_exam.id;
                    ALTER TABLE vmlc_leaderboardsnapshot DROP COLUMN exam_id CASCADE;
                    ALTER TABLE vmlc_leaderboardsnapshot RENAME COLUMN exam_uuid TO exam_id;
                    -- We leave it as a loose column (or Django will manage it later if added back to model)
                    -- FK constraint is dropped by CASCADE or explicitly
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),

        # 6. Remove old fields (Django side)
        migrations.RemoveField(
            model_name='candidatescore',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='id',
        ),

        # 7. M2M Cleanup
        migrations.RunSQL(
            "ALTER TABLE vmlc_exam_questions DROP COLUMN exam_id;",
            reverse_sql=migrations.RunSQL.noop
        ),

        # 8. Switch Exam PK
        migrations.RenameField(
            model_name='exam',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),

        # 9. Restore CandidateScore
        migrations.RenameField(
            model_name='candidatescore',
            old_name='exam_uuid',
            new_name='exam',
        ),
        migrations.AlterField(
            model_name='candidatescore',
            name='exam',
            field=models.ForeignKey(on_delete=models.PROTECT, related_name='scores', to='vmlc.exam'),
        ),

        # 10. Restore M2M Constraint
        migrations.RunSQL(
            """
            ALTER TABLE vmlc_exam_questions RENAME COLUMN exam_uuid TO exam_id;
            ALTER TABLE vmlc_exam_questions ALTER COLUMN exam_id SET NOT NULL;
            ALTER TABLE vmlc_exam_questions ADD CONSTRAINT vmlc_exam_questions_exam_id_fk_vmlc_exam_id 
                FOREIGN KEY (exam_id) REFERENCES vmlc_exam(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]