# Generated by Django 5.2.6 on 2026-01-18 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0032_alter_exam_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
