# Generated by Django 5.2.6 on 2026-01-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0033_alter_exam_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="candidate",
            name="vmlc_candid_school_09464a_idx",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="school",
            new_name="school_name",
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["school_name"], name="vmlc_candid_school__3d4ff7_idx"
            ),
        ),
    ]
