# Generated by Django 5.2.6 on 2026-01-21 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0035_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportinquiry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Support Inquiry",
                "verbose_name_plural": "Support Inquiries",
            },
        ),
        migrations.AddField(
            model_name="supportinquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supportinquiry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="supportinquiry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user who submitted the inquiry, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="supportinquiry",
            name="message",
            field=models.TextField(help_text="Initial message from the user."),
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "sender_profile",
                    models.CharField(
                        help_text="The role of the sender at the time the message was sent.",
                        max_length=50,
                    ),
                ),
                ("text", models.TextField()),
                ("is_read_by_staff", models.BooleanField(db_index=True, default=False)),
                ("is_read_by_user", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="vmlc.supportinquiry",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_support_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Message",
                "verbose_name_plural": "Support Messages",
                "ordering": ["created_at"],
            },
        ),
    ]
