# Generated by Django 5.2.6 on 2026-01-27 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0036_alter_supportinquiry_options_supportinquiry_status_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CandidateScoreSnapshot",
            new_name="CandidateExamResultSnapshot",
        ),
        migrations.RenameModel(
            old_name="CandidateScore",
            new_name="CandidateExamResult",
        ),
        migrations.RenameField(
            model_name="candidateanswer",
            old_name="candidate_score",
            new_name="candidate_exam_result",
        ),
        migrations.AlterField(
            model_name="candidateexamresultsnapshot",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_exam_result_snapshots",
                to="vmlc.staff",
            ),
        ),
    ]
