# Generated by Django 5.2.6 on 2026-01-27 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vmlc",
            "0037_rename_candidatescoresnapshot_candidateexamresultsnapshot_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="candidateanswer",
            name="unique_answer_per_candidate_score",
        ),
        migrations.AlterField(
            model_name="candidateexamresult",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="vmlc.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="candidateexamresult",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="vmlc.exam",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateanswer",
            constraint=models.UniqueConstraint(
                fields=("candidate_exam_result", "question"),
                name="unique_answer_per_candidate_exam_result",
            ),
        ),
    ]
