# Generated by Django 5.2.6 on 2026-01-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0007_alter_broadcast_created_by"),
        ("identity", "0001_initial"),
        ("vmlc", "0001_initial"),
    ]

    operations = [
        # No state operations needed for fresh databases
        # For existing databases that went through the old migration path,
        # this migration was already applied when it had the full
        # SeparateDatabaseAndState operations
    ]
