# Generated by Django 5.2.6 on 2026-01-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0007_alter_broadcast_created_by"),
        ("identity", "0001_initial"),
        (
            "vmlc",
            "0038_remove_candidateanswer_unique_answer_per_candidate_score_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Remove models from vmlc app state
                migrations.RemoveField(
                    model_name="candidate",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="candidate",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="emailotp",
                    name="user",
                ),
                migrations.DeleteModel(
                    name="PreRegUser",
                ),
                migrations.RemoveField(
                    model_name="staff",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="staff",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="userverification",
                    name="action_by",
                ),
                migrations.RemoveField(
                    model_name="user",
                    name="groups",
                ),
                migrations.RemoveField(
                    model_name="user",
                    name="user_permissions",
                ),
                migrations.RemoveField(
                    model_name="userverification",
                    name="user",
                ),
                migrations.DeleteModel(
                    name="Candidate",
                ),
                migrations.DeleteModel(
                    name="EmailOTP",
                ),
                migrations.DeleteModel(
                    name="Staff",
                ),
                migrations.DeleteModel(
                    name="User",
                ),
                migrations.DeleteModel(
                    name="UserVerification",
                ),
                # Update ForeignKeys to point to the new identity models (state only)
                migrations.AlterField(
                    model_name="candidateexamresult",
                    name="candidate",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="identity.candidate",
                    ),
                ),
                migrations.AlterField(
                    model_name="candidateexamresult",
                    name="score_submitted_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="identity.staff",
                    ),
                ),
                migrations.AlterField(
                    model_name="exam",
                    name="updated_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams_updated",
                        to="identity.staff",
                    ),
                ),
                migrations.AlterField(
                    model_name="question",
                    name="created_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_created",
                        to="identity.staff",
                    ),
                ),
                migrations.AlterField(
                    model_name="candidateexamresultsnapshot",
                    name="published_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_exam_result_snapshots",
                        to="identity.staff",
                    ),
                ),
                migrations.AlterField(
                    model_name="exam",
                    name="created_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams_created",
                        to="identity.staff",
                    ),
                ),
                migrations.AlterField(
                    model_name="question",
                    name="updated_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_updated",
                        to="identity.staff",
                    ),
                ),
                migrations.AlterField(
                    model_name="leaderboardsnapshot",
                    name="published_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leaderboard_snapshots",
                        to="identity.staff",
                    ),
                ),
            ],
            database_operations=[],  # No actual database changes needed
        ),
    ]