# Generated by Django 5.2.6 on 2026-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("vmlc", "0039_remove_candidate_created_by_remove_candidate_user_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="exam",
            name="vmlc_exam_stage_91a198_idx",
        ),
        migrations.RenameField(
            model_name="exam",
            old_name="level",
            new_name="round",
        ),
        migrations.AlterField(
            model_name="exam",
            name="round",
            field=models.PositiveIntegerField(
                db_index=True,
                default=1,
                help_text="Round within the stage (e.g., 1 for League 1, 2 for League 2)",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["stage", "round", "is_active"],
                name="vmlc_exam_stage_ece6e5_idx",
            ),
        ),
    ]