# Generated by Django 5.2.6 on 2026-01-28 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("vmlc", "0040_rename_exam_vmlc_exam_stage_91a198_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "facilitator_system",
                    models.CharField(
                        choices=[("vmlc", "VMLC"), ("esturdi", "Esturdi")],
                        max_length=20,
                    ),
                ),
                (
                    "access_url",
                    models.URLField(
                        blank=True,
                        help_text="Candidate-specific exam URL on the facilitator.",
                        null=True,
                    ),
                ),
                (
                    "passcode",
                    models.CharField(
                        blank=True,
                        help_text="Opaque passcode or token embedded in the URL.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("issued", "Issued"),
                            ("started", "Started"),
                            ("submitted", "Submitted"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "facilitator_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw request/response metadata exchanged with facilitator.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_accesses",
                        to="identity.candidate",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_records",
                        to="vmlc.exam",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["exam", "status"], name="vmlc_examac_exam_id_4012f5_idx"
                    ),
                    models.Index(
                        fields=["candidate", "status"],
                        name="vmlc_examac_candida_1413f3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exam", "candidate"),
                        name="unique_exam_access_per_candidate",
                    )
                ],
            },
        ),
    ]
