# Generated by Django 5.2.6 on 2026-01-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0041_examaccess"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="exam",
            name="vmlc_exam_stage_ece6e5_idx",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="round",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="stage",
        ),
    ]
