# Generated by Django 5.2.6 on 2026-01-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vmlc", "0042_remove_exam_vmlc_exam_stage_ece6e5_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="delivery_mode",
            field=models.CharField(
                choices=[
                    ("online", "Online (Remote)"),
                    ("in_person", "In-Person (CBT Venue)"),
                ],
                db_index=True,
                default="online",
                max_length=20,
            ),
        ),
    ]
