# Generated by Django 5.2.6 on 2026-01-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0007_remove_stageexam_unique_exam_per_stage_and_more"),
        ("vmlc", "0043_exam_delivery_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="title",
        ),
        migrations.AddField(
            model_name="exam",
            name="competition_slot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exam",
                to="competition.stageexam",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_a",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_b",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_c",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_d",
            field=models.TextField(blank=True),
        ),
    ]
