# Generated by Django 5.2.6 on 2026-01-30 12:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vmlc", "0044_remove_exam_title_exam_competition_slot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("moderate", "Moderate"), ("hard", "Hard")],
                default="moderate",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="supportmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
