# Generated by Django 5.2.6 on 2026-02-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0046_alter_candidateanswer_candidate_exam_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="countdown_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="open_duration_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
