# Generated by Django 5.2.6 on 2026-02-08 03:31

from django.db import migrations, models

import identity.validators
import vmlc.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("vmlc", "0047_alter_exam_countdown_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PublicMediaStorage(),
                upload_to="question_images/",
                validators=[identity.validators.validate_image],
            ),
        ),
    ]
