# Generated by Django 5.2.6 on 2026-02-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0048_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="examaccess",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
