# Generated by Django 5.2.6 on 2026-02-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competition",
            "0010_remove_rankingsnapshot_unique_standings_per_exam_and_more",
        ),
        ("vmlc", "0049_examaccess_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="competition_slot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam",
                to="competition.stageexam",
            ),
        ),
    ]
