# Generated by Django 5.2.6 on 2026-02-13 18:29

import vmlc.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0050_alter_exam_competition_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="examaccess",
            name="face_capture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=vmlc.storage_backends.PrivateMediaStorage(),
                upload_to="exam_face_captures/",
            ),
        ),
        migrations.AddField(
            model_name="examaccess",
            name="is_passcode_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the passcode email has been sent to the candidate.",
            ),
        ),
        migrations.AddField(
            model_name="examaccess",
            name="is_passcode_used",
            field=models.BooleanField(
                default=False,
                help_text="Whether the passcode has been used for direct access.",
            ),
        ),
    ]
