# Generated by Django 5.2.6 on 2026-02-14 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0051_examaccess_face_capture_examaccess_is_passcode_sent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examaccess",
            name="access_url",
        ),
        migrations.RemoveField(
            model_name="examaccess",
            name="is_passcode_sent",
        ),
        migrations.RemoveField(
            model_name="examaccess",
            name="is_passcode_used",
        ),
        migrations.RemoveField(
            model_name="examaccess",
            name="passcode",
        ),
        migrations.AlterField(
            model_name="examaccess",
            name="facilitator_system",
            field=models.CharField(
                choices=[("vmlc", "VMLC"), ("esturdi", "Esturdi")],
                default="vmlc",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExamAccessPasscode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_url",
                    models.URLField(
                        blank=True,
                        help_text="Candidate-specific exam URL on the facilitator.",
                        null=True,
                    ),
                ),
                (
                    "passcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Opaque passcode or token embedded in the URL.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "is_passcode_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the passcode email has been sent to the candidate.",
                    ),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_access",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_access",
                        to="vmlc.examaccess",
                    ),
                ),
            ],
        ),
    ]
