# Generated by Django 5.2.6 on 2026-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0052_remove_examaccess_access_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Management",
                "verbose_name_plural": "Cache Management",
                "managed": False,
            },
        ),
    ]
