# Generated by Django 5.2.6 on 2026-02-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0053_cachemanagement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportmessage",
            name="inquiry",
        ),
        migrations.RemoveField(
            model_name="supportmessage",
            name="sender",
        ),
        migrations.DeleteModel(
            name="SupportInquiry",
        ),
        migrations.DeleteModel(
            name="SupportMessage",
        ),
    ]
