# Generated by Django 5.2.6 on 2026-02-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0053_cachemanagement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportmessage",
            name="inquiry",
        ),
        migrations.RemoveField(
            model_name="supportmessage",
            name="sender",
        ),
        migrations.AddField(
            model_name="exam",
            name="_status_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("ongoing", "Ongoing"),
                    ("concluded", "Concluded"),
                    ("cancelled", "Cancelled"),
                ],
                help_text="For testing only: temporarily override the computed status.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="SupportInquiry",
        ),
        migrations.DeleteModel(
            name="SupportMessage",
        ),
    ]
