# Generated by Django 5.2.6 on 2026-02-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0054_remove_supportmessage_inquiry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="_status_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("ongoing", "Ongoing"),
                    ("concluded", "Concluded"),
                    ("cancelled", "Cancelled"),
                ],
                help_text="For testing only: temporarily override the computed status.",
                max_length=20,
                null=True,
            ),
        ),
    ]
