# Generated by Django 5.2.6 on 2026-03-14 01:05

import uuid

import django.db.models.deletion
from django.db import migrations, models

import vmlc.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("vmlc", "0055_alter_candidateanswer_candidate_exam_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamHeartbeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        help_text="Sequential index of the heartbeat to detect gaps."
                    ),
                ),
                (
                    "client_uuid",
                    models.UUIDField(
                        help_text="Idempotency key generated by the client.",
                        unique=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "period_start",
                    models.DateTimeField(help_text="Start of the telemetry interval."),
                ),
                (
                    "period_end",
                    models.DateTimeField(help_text="End of the telemetry interval."),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Aggregated counts of violation types.",
                    ),
                ),
                (
                    "face_capture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=vmlc.storage_backends.PrivateMediaStorage(),
                        upload_to="exam_heartbeats/",
                    ),
                ),
                (
                    "suspicion_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Computed score for this specific heartbeat (0.0 - 1.0).",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Client environment metadata (OS, Browser, etc.).",
                    ),
                ),
                (
                    "exam_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeats",
                        to="vmlc.examaccess",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="ViolationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                (
                    "timestamp",
                    models.DateTimeField(help_text="Precise time the event occurred."),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this event should trigger immediate attention.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contextual info (question_id, duration, etc.).",
                    ),
                ),
                (
                    "heartbeat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="vmlc.examheartbeat",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="examheartbeat",
            index=models.Index(
                fields=["exam_access", "sequence_number"],
                name="vmlc_examhe_exam_ac_6dedce_idx",
            ),
        ),
    ]
