# Generated by Django 5.2.6 on 2026-03-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vmlc", "0056_examheartbeat_violationevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examaccess",
            name="is_manually_reviewed",
            field=models.BooleanField(
                default=False,
                help_text="Whether an admin has manually confirmed or cleared this attempt.",
            ),
        ),
        migrations.AddField(
            model_name="examaccess",
            name="proctoring_status",
            field=models.CharField(
                choices=[
                    ("clear", "Clear"),
                    ("suspicious", "Suspicious"),
                    ("flagged", "Flagged"),
                ],
                db_index=True,
                default="clear",
                max_length=20,
            ),
        ),
    ]
