# Generated by Django 5.2.6 on 2026-04-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0059_auto_20260314_0255"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateexamresult",
            name="is_auto_submit",
            field=models.BooleanField(default=False),
        ),
    ]
