# Generated by Django 5.2.6 on 2026-04-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_alter_cowrywisekidprofile_options"),
        ("vmlc", "0060_candidateexamresult_is_auto_submit"),
    ]

    operations = [
        migrations.AddField(
            model_name="examaccess",
            name="is_unlocked",
            field=models.BooleanField(
                default=False,
                help_text="Whether this session has been unlocked via QR code (for final exams).",
            ),
        ),
        migrations.AddField(
            model_name="examaccess",
            name="unlocked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The admin who scanned the QR code to unlock this session.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unlocked_exams",
                to="identity.staff",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="delivery_mode",
            field=models.CharField(
                choices=[
                    ("virtual", "Virtual"),
                    ("in_person", "In-Person (CBT Venue)"),
                ],
                db_index=True,
                default="virtual",
                max_length=20,
            ),
        ),
    ]
