# Generated by Django 5.2.6 on 2026-05-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vmlc", "0061_examaccess_is_unlocked_examaccess_unlocked_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaderboardsnapshot",
            name="published_by",
        ),
        migrations.DeleteModel(
            name="CandidateExamResultSnapshot",
        ),
        migrations.DeleteModel(
            name="LeaderboardSnapshot",
        ),
    ]
