# Generated by Django 5.2.6 on 2025-09-24 23:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mediums",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("platform", "Platform"),
                                ("email", "Email"),
                                ("whatsapp", "WhatsApp"),
                                ("sms", "SMS"),
                            ],
                            max_length=20,
                        ),
                        default=list,
                        help_text="List of mediums to use (Email, SMS, Platform, etc.)",
                        size=None,
                    ),
                ),
                (
                    "target_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("screening", "Screening"),
                                ("league", "League"),
                                ("final", "Final"),
                                ("winner", "Winner"),
                            ],
                            max_length=20,
                        ),
                        default=list,
                        help_text="List of target roles to broadcast to (Screening, League, Final, Winner)",
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("sent", "Sent"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Overall broadcast status",
                        max_length=20,
                    ),
                ),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts",
                        to="identity.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BroadcastLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "medium",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("league", "League"),
                            ("final", "Final"),
                            ("winner", "Winner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, help_text="Error or status message"),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="comms.broadcast",
                    ),
                ),
            ],
        ),
    ]
