# Generated by Django 5.2.6 on 2025-09-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for tracking",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("failed_to_queue", "Failed to Queue"),
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("sent", "Sent"),
                    ("partial", "Partial Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Overall broadcast status",
                max_length=20,
            ),
        ),
    ]
