# Generated by Django 5.2.6 on 2025-11-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcastlog",
            name="role_type",
            field=models.CharField(
                choices=[("staff", "Staff"), ("candidate", "Candidate")],
                default="candidate",
                help_text="Whether this is a staff or candidate role",
                max_length=10,
            ),
            preserve_default=False,
        ),
        # This RunSQL operation is to handle the array -> JSONB conversion
        migrations.RunSQL(
            sql="""
                ALTER TABLE comms_broadcast 
                ALTER COLUMN target_roles TYPE jsonb 
                USING to_jsonb(target_roles);
            """,
            reverse_sql="""
                ALTER TABLE comms_broadcast 
                ALTER COLUMN target_roles TYPE character varying[] 
                USING ARRAY(SELECT jsonb_array_elements_text(target_roles));
            """,
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="target_roles",
            field=models.JSONField(
                default=dict,
                help_text='\n        Dictionary of target roles to broadcast to:\n        {\n            "staff": ["volunteer", "moderator", "admin", "manager", "superadmin"],\n            "candidate": ["screening", "league", "final", "winner"]\n        }\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="broadcastlog",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("screening", "Screening"),
                    ("league", "League"),
                    ("final", "Final"),
                    ("winner", "Winner"),
                    ("superadmin", "Superadmin"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                    ("sponsor", "Sponsor"),
                    ("volunteer", "Volunteer"),
                ],
                max_length=20,
            ),
        ),
    ]
