# Generated by Django 5.2.6 on 2025-12-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0004_broadcastlog_role_type_alter_broadcast_target_roles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastlog",
            name="role_type",
            field=models.CharField(
                choices=[("staff", "Staff"), ("candidate", "Candidate")],
                default="candidate",
                help_text="Whether this is a staff or candidate role",
                max_length=10,
            ),
        ),
    ]
