# Generated by Django 5.2.6 on 2025-12-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0005_alter_broadcastlog_role_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("first_failure", "First Failure"),
                            ("final_failure", "Final Failure"),
                            ("success_after_retry", "Success After Retry"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[("prod", "Production"), ("staging", "Staging")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("backup_filename", models.CharField(max_length=255)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
