# Generated by Django 5.2.6 on 2026-01-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0006_backuplog"),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broadcasts",
                to="identity.staff",
            ),
        ),
    ]
