# Generated by Django 5.2.6 on 2026-02-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0007_alter_broadcast_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="read",
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read_by_recipient",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("alert", "Alert"),
                    ("info", "Information"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="alert",
                max_length=20,
            ),
        ),
    ]
