# Generated by Django 5.2.6 on 2026-02-04 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comms", "0008_remove_notification_read_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backuplog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Backup Log",
                "verbose_name_plural": "Backup Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="broadcast",
            options={"verbose_name": "Broadcast", "verbose_name_plural": "Broadcasts"},
        ),
        migrations.AlterModelOptions(
            name="broadcastlog",
            options={
                "verbose_name": "Broadcast Log",
                "verbose_name_plural": "Broadcast Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
