# Generated by Django 5.2.6 on 2026-02-18 12:27

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0009_alter_backuplog_options_alter_broadcast_options_and_more"),
        ("identity", "0002_alter_user_profile_picture_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicSupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(max_length=255)),
                ("organization", models.CharField(blank=True, max_length=255)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Nigerian phone number.",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+234XXXXXXXXXX' or '0XXXXXXXXXX'",
                                regex="^(\\+234[789][01]\\d{8}|0[789][01]\\d{8})$",
                            )
                        ],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sponsorship", "Sponsorship"),
                            ("partnership", "Partnership"),
                            ("media_publiciy", "Media/Publicity"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="Message from the user.")),
                ("consent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Public Support Request",
                "verbose_name_plural": "Public Support Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="broadcast",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Broadcast",
                "verbose_name_plural": "Broadcasts",
            },
        ),
        migrations.AlterModelOptions(
            name="broadcastlog",
            options={
                "ordering": ["-attempted_at"],
                "verbose_name": "Broadcast Log",
                "verbose_name_plural": "Broadcast Logs",
            },
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="is_read_by_recipient",
            new_name="is_read",
        ),
        migrations.AddField(
            model_name="broadcast",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this broadcast has been retried after partial or total failure.",
            ),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Future date/time when this broadcast should be dispatched. If null, sent immediately.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The timestamp when the broadcast successfully completed all delivery paths.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="total_recipients",
            field=models.IntegerField(
                default=0,
                help_text="Total number of unique users targeted by this broadcast.",
            ),
        ),
        migrations.AddField(
            model_name="broadcastlog",
            name="recipient_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of recipients within this specific medium-role slice.",
            ),
        ),
        migrations.AddField(
            model_name="broadcastlog",
            name="sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The timestamp when this specific delivery path finished.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="last_attempt",
            field=models.DateTimeField(
                blank=True,
                help_text="The timestamp of the most recent delivery attempt.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="mediums",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("platform", "Platform"),
                        ("email", "Email"),
                        ("whatsapp", "WhatsApp"),
                        ("sms", "SMS"),
                    ],
                    max_length=20,
                ),
                default=list,
                help_text="Ordered list of delivery mediums (Email, SMS, Platform, WhatsApp).",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("failed_to_queue", "Failed to Queue"),
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("sent", "Sent"),
                    ("partial", "Partial Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Overall broadcast delivery status.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="target_roles",
            field=models.JSONField(
                default=dict,
                help_text='Dictionary of role groups to target. Valid structure: {"staff": ["volunteer", "moderator", ...], "candidate": ["screening", "league", ...]}',
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for async tracking and potential cancellation.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="broadcastlog",
            name="message",
            field=models.TextField(blank=True, help_text="Error or status message."),
        ),
        migrations.AlterField(
            model_name="broadcastlog",
            name="role_type",
            field=models.CharField(
                choices=[("staff", "Staff"), ("candidate", "Candidate")],
                default="candidate",
                help_text="Whether this log entry targets a staff or candidate role.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SupportChatThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_chat_threads",
                        to="identity.staff",
                    ),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        help_text="Candidate who owns this support thread.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_chat_thread",
                        to="identity.candidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Chat Thread",
                "verbose_name_plural": "Support Chat Threads",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreadMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("staff", "Staff"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_support_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="comms.supportchatthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="comms.threadmessage",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="supportchatthread",
            index=models.Index(
                fields=["last_message_at"], name="comms_suppo_last_me_b82e68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportchatthread",
            index=models.Index(
                fields=["assigned_staff"], name="comms_suppo_assigne_b83bd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="threadmessage",
            index=models.Index(
                fields=["thread", "created_at"], name="comms_threa_thread__a152a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageread",
            index=models.Index(fields=["user"], name="comms_messa_user_id_a2197f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="messageread",
            unique_together={("message", "user")},
        ),
    ]
