# Generated by Django 5.2.6 on 2026-02-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0010_publicsupportrequest_alter_broadcast_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="sms_message",
            field=models.TextField(
                blank=True,
                help_text="Optional shorter message for SMS/WhatsApp. If blank, the main message is condensed automatically.",
                null=True,
            ),
        ),
    ]
