# Generated by Django 5.2.6 on 2026-02-19 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0010_publicsupportrequest_alter_broadcast_options_and_more"),
        ("identity", "0002_alter_user_profile_picture_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportchatthread",
            name="assigned_staff",
        ),
        migrations.RemoveField(
            model_name="supportchatthread",
            name="candidate",
        ),
        migrations.AlterField(
            model_name="threadmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_helpdesk_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="HelpdeskThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_helpdesk_threads",
                        to="identity.staff",
                    ),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        help_text="Candidate who owns this helpdesk thread.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpdesk_thread",
                        to="identity.candidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Helpdesk Thread",
                "verbose_name_plural": "Helpdesk Threads",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.AlterField(
            model_name="threadmessage",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="comms.helpdeskthread",
            ),
        ),
        migrations.AddIndex(
            model_name="helpdeskthread",
            index=models.Index(
                fields=["last_message_at"], name="comms_helpd_last_me_f3d016_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpdeskthread",
            index=models.Index(
                fields=["assigned_staff"], name="comms_helpd_assigne_73f6e3_idx"
            ),
        ),
        migrations.DeleteModel(
            name="SupportChatThread",
        ),
    ]
