# Generated by Django 5.2.6 on 2026-03-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0011_broadcast_sms_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpdeskthread",
            name="snoozed_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="helpdeskthread",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("closed", "Closed"),
                    ("snoozed", "Snoozed"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
