# Generated by Django 5.2.6 on 2026-01-28 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(db_index=True)),
                (
                    "start_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("concluded", "Concluded"),
                        ],
                        db_index=True,
                        default="upcoming",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Competition-level configuration flags and thresholds.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CandidateCompetition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("active", "Active"),
                            ("eliminated", "Eliminated"),
                            ("withdrawn", "Withdrawn"),
                            ("disqualified", "Disqualified"),
                        ],
                        db_index=True,
                        default="enrolled",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Competition-specific data about the candidate.",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitions",
                        to="identity.candidate",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="competition.competition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("league", "League"),
                            ("final", "Final"),
                        ],
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("description", models.TextField()),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="competition.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CandidateStageProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="pending",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("discontinued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_progress",
                        to="competition.candidatecompetition",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.stage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidatecompetition",
            name="current_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="The candidate's current stage in the competition.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="competition.stage",
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("competition", "type"), name="unique_stage_per_competition"
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("competition", "order"),
                name="unique_stage_order_per_competition",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatestageprogress",
            constraint=models.UniqueConstraint(
                fields=("candidate_competition", "stage"),
                name="unique_stage_progress_per_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatecompetition",
            constraint=models.UniqueConstraint(
                fields=("candidate", "competition"),
                name="unique_candidate_per_competition",
            ),
        ),
    ]
