# Generated by Django 5.2.6 on 2026-01-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
        ("identity", "0001_initial"),
        ("vmlc", "0039_remove_candidate_created_by_remove_candidate_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Standings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("league", "League"),
                            ("final", "Final"),
                        ],
                        help_text="Competition stage this standings belongs to (screening, league, final).",
                        max_length=20,
                    ),
                ),
                (
                    "round",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="League round/week number. Null for screening and final.",
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this standings is visible to candidates.",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Auxiliary metadata (e.g. exam engine used: vmlc or esturdi).",
                    ),
                ),
                (
                    "data_json",
                    models.JSONField(
                        blank=True,
                        help_text="Optional denormalized export for caching or external consumption.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standings",
                        to="competition.competition",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        help_text="Exam from which this standings was generated.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vmlc.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StandingsEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Candidate's exam score used for ranking.",
                        max_digits=5,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("percentile", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings_entries",
                        to="identity.candidate",
                    ),
                ),
                (
                    "candidate_competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standings_entries",
                        to="competition.candidatecompetition",
                    ),
                ),
                (
                    "standings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="competition.standings",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="standings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_published", True)),
                fields=("competition", "stage", "round"),
                name="one_published_standings_per_stage_round",
            ),
        ),
        migrations.AddIndex(
            model_name="standingsentry",
            index=models.Index(
                fields=["standings", "rank"], name="competition_standin_dcc9bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standingsentry",
            index=models.Index(
                fields=["standings", "candidate"], name="competition_standin_136881_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="standingsentry",
            constraint=models.UniqueConstraint(
                fields=("standings", "candidate"), name="unique_candidate_per_standings"
            ),
        ),
    ]
