# Generated by Django 5.2.6 on 2026-01-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0002_standings_standingsentry_and_more"),
        ("identity", "0001_initial"),
        ("vmlc", "0039_remove_candidate_created_by_remove_candidate_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregateLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("league", "League"),
                            ("final", "Final"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "as_of_round",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AggregateLeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=10)),
                ("overall_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="standings",
            name="facilitator_system",
            field=models.CharField(
                choices=[("vmlc", "VMLC"), ("esturdi", "Esturdi")],
                default="vmlc",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="standingsentry",
            name="tie_break_reason",
            field=models.CharField(
                blank=True,
                help_text="Optional explanation when tie-break applied.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="standings",
            index=models.Index(
                fields=["competition", "stage", "round", "is_published"],
                name="competition_competi_e8e1ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="standingsentry",
            index=models.Index(
                fields=["standings", "exam_score"],
                name="competition_standin_83c057_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="standings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exam__isnull", False)),
                fields=("exam",),
                name="unique_standings_per_exam",
            ),
        ),
        migrations.AddField(
            model_name="aggregateleaderboard",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="competition.competition",
            ),
        ),
        migrations.AddField(
            model_name="aggregateleaderboardentry",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="identity.candidate"
            ),
        ),
        migrations.AddField(
            model_name="aggregateleaderboardentry",
            name="candidate_competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="competition.candidatecompetition",
            ),
        ),
        migrations.AddField(
            model_name="aggregateleaderboardentry",
            name="leaderboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="competition.aggregateleaderboard",
            ),
        ),
        migrations.AddIndex(
            model_name="aggregateleaderboard",
            index=models.Index(
                fields=["competition", "stage", "as_of_round"],
                name="competition_competi_d56253_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aggregateleaderboardentry",
            index=models.Index(
                fields=["leaderboard", "overall_rank"],
                name="competition_leaderb_f5d53f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aggregateleaderboardentry",
            index=models.Index(
                fields=["leaderboard", "candidate"],
                name="competition_leaderb_43dca4_idx",
            ),
        ),
    ]
