# Generated by Django 5.2.6 on 2026-01-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0003_aggregateleaderboard_aggregateleaderboardentry_and_more"),
        ("vmlc", "0041_examaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Round number within this stage (e.g., Week 1, Week 2 for League stages).",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this exam currently part of the active competition flow?",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="StageExam-specific config."
                    ),
                ),
                (
                    "competition_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_exams",
                        to="competition.stage",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_contexts",
                        to="vmlc.exam",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("competition_stage", "exam"),
                        name="unique_exam_per_stage",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("round__isnull", False)),
                        fields=("competition_stage", "round"),
                        name="unique_round_per_stage",
                    ),
                ],
            },
        ),
    ]
