# Generated by Django 5.2.6 on 2026-01-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0005_create_stage_exams_from_vmlc_exams"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
