# Generated by Django 5.2.6 on 2026-01-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0006_competition_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stageexam",
            name="unique_exam_per_stage",
        ),
        migrations.RenameField(
            model_name="competition",
            old_name="year",
            new_name="edition",
        ),
        migrations.RemoveField(
            model_name="stageexam",
            name="exam",
        ),
        migrations.AlterField(
            model_name="stage",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="stageexam",
            name="round",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Round within this stage (e.g., Week 1, Week 2 for League stages).",
                null=True,
            ),
        ),
    ]
