# Generated by Django 5.2.6 on 2026-02-03 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0007_remove_stageexam_unique_exam_per_stage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatecompetition",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("eliminated", "Eliminated"),
                    ("disqualified", "Disqualified"),
                ],
                db_index=True,
                default="active",
            ),
        ),
        migrations.AlterField(
            model_name="candidatestageprogress",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="competition.stage"
            ),
        ),
        migrations.AlterField(
            model_name="stageexam",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Is this exam currently part of the active competition flow?",
            ),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="standings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="competition.standings",
            ),
        ),
    ]
