# Generated by Django 5.2.6 on 2026-02-04 18:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0008_alter_candidatecompetition_status_and_more"),
        ("identity", "0002_alter_user_profile_picture_and_more"),
        ("vmlc", "0047_alter_exam_countdown_minutes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aggregateleaderboardentry",
            name="leaderboard",
        ),
        migrations.RemoveField(
            model_name="aggregateleaderboardentry",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="aggregateleaderboardentry",
            name="candidate_competition",
        ),
        migrations.RemoveField(
            model_name="candidatecompetition",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="candidatecompetition",
            name="competition",
        ),
        migrations.RemoveField(
            model_name="candidatecompetition",
            name="current_stage",
        ),
        migrations.RemoveField(
            model_name="candidatestageprogress",
            name="candidate_competition",
        ),
        migrations.RemoveField(
            model_name="standingsentry",
            name="candidate_competition",
        ),
        migrations.RemoveField(
            model_name="candidatestageprogress",
            name="stage",
        ),
        migrations.RemoveField(
            model_name="standings",
            name="competition",
        ),
        migrations.RemoveField(
            model_name="standings",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="standingsentry",
            name="standings",
        ),
        migrations.RemoveField(
            model_name="standingsentry",
            name="candidate",
        ),
        migrations.AlterModelOptions(
            name="stage",
            options={
                "ordering": ["order"],
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
            },
        ),
        migrations.AlterModelOptions(
            name="stageexam",
            options={
                "verbose_name": "Stage Exam",
                "verbose_name_plural": "Stage Exams",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("eliminated", "Eliminated"),
                            ("disqualified", "Disqualified"),
                        ],
                        db_index=True,
                        default="active",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Competition-specific data about the candidate.",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitions",
                        to="identity.candidate",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="competition.competition",
                    ),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        blank=True,
                        help_text="The candidate's current stage in the competition.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="competition.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
            },
        ),
        migrations.CreateModel(
            name="EnrollmentStageProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="pending",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("discontinued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_progress",
                        to="competition.enrollment",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="competition.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment Stage Progress",
                "verbose_name_plural": "Enrollment Stage Progress Records",
            },
        ),
        migrations.CreateModel(
            name="LeagueLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("league", "League"),
                            ("final", "Final"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "as_of_round",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="competition.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "League Leaderboard",
                "verbose_name_plural": "League Leaderboards",
            },
        ),
        migrations.CreateModel(
            name="LeagueLeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=10)),
                ("overall_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.candidate",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="competition.enrollment",
                    ),
                ),
                (
                    "leaderboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="competition.leagueleaderboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "League Leaderboard Entry",
                "verbose_name_plural": "League Leaderboard Entries",
            },
        ),
        migrations.CreateModel(
            name="RankingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("screening", "Screening"),
                            ("league", "League"),
                            ("final", "Final"),
                        ],
                        help_text="Competition stage this ranking snapshot belongs to (screening, league, final).",
                        max_length=20,
                    ),
                ),
                (
                    "round",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="League round/week number. Null for screening and final.",
                        null=True,
                    ),
                ),
                (
                    "facilitator_system",
                    models.CharField(
                        choices=[("vmlc", "VMLC"), ("esturdi", "Esturdi")],
                        default="vmlc",
                        max_length=20,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this ranking snapshot is visible to candidates.",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Auxiliary metadata (e.g. exam engine used: vmlc or esturdi).",
                    ),
                ),
                (
                    "data_json",
                    models.JSONField(
                        blank=True,
                        help_text="Optional denormalized export for caching or external consumption.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ranking_snapshots",
                        to="competition.competition",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        help_text="Exam from which this ranking snapshot was generated.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vmlc.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking Snapshot",
                "verbose_name_plural": "Ranking Snapshots",
            },
        ),
        migrations.CreateModel(
            name="RankingSnapshotEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Candidate's exam score used for ranking.",
                        max_digits=5,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "tie_break_reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional explanation when tie-break applied.",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("percentile", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_snapshot_entries",
                        to="identity.candidate",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ranking_snapshot_entries",
                        to="competition.enrollment",
                    ),
                ),
                (
                    "ranking_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="competition.rankingsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking Snapshot Entry",
                "verbose_name_plural": "Ranking Snapshot Entries",
            },
        ),
        migrations.DeleteModel(
            name="AggregateLeaderboard",
        ),
        migrations.DeleteModel(
            name="AggregateLeaderboardEntry",
        ),
        migrations.DeleteModel(
            name="CandidateCompetition",
        ),
        migrations.DeleteModel(
            name="CandidateStageProgress",
        ),
        migrations.DeleteModel(
            name="Standings",
        ),
        migrations.DeleteModel(
            name="StandingsEntry",
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("candidate", "competition"),
                name="unique_candidate_per_competition",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentstageprogress",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "stage"),
                name="unique_stage_progress_per_candidate",
            ),
        ),
        migrations.AddIndex(
            model_name="leagueleaderboard",
            index=models.Index(
                fields=["competition", "stage", "as_of_round"],
                name="competition_competi_a31740_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leagueleaderboardentry",
            index=models.Index(
                fields=["leaderboard", "overall_rank"],
                name="competition_leaderb_3a62df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leagueleaderboardentry",
            index=models.Index(
                fields=["leaderboard", "candidate"],
                name="competition_leaderb_d9f33c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rankingsnapshot",
            index=models.Index(
                fields=["competition", "stage", "round", "is_published"],
                name="competition_competi_258759_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exam__isnull", False)),
                fields=("exam",),
                name="unique_standings_per_exam",
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_published", True)),
                fields=("competition", "stage", "round"),
                name="one_published_standings_per_stage_round",
            ),
        ),
        migrations.AddIndex(
            model_name="rankingsnapshotentry",
            index=models.Index(
                fields=["ranking_snapshot", "rank"],
                name="competition_ranking_38ffd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rankingsnapshotentry",
            index=models.Index(
                fields=["ranking_snapshot", "candidate"],
                name="competition_ranking_df7213_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rankingsnapshotentry",
            index=models.Index(
                fields=["ranking_snapshot", "exam_score"],
                name="competition_ranking_729720_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingsnapshotentry",
            constraint=models.UniqueConstraint(
                fields=("ranking_snapshot", "candidate"),
                name="unique_candidate_per_ranking_snapshot",
            ),
        ),
    ]
