# Generated by Django 5.2.6 on 2026-02-08 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0009_remove_aggregateleaderboardentry_leaderboard_and_more"),
        ("identity", "0002_alter_user_profile_picture_and_more"),
        ("vmlc", "0048_question_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rankingsnapshot",
            name="unique_standings_per_exam",
        ),
        migrations.RemoveConstraint(
            model_name="rankingsnapshot",
            name="one_published_standings_per_stage_round",
        ),
        migrations.RemoveConstraint(
            model_name="rankingsnapshotentry",
            name="unique_candidate_per_ranking_snapshot",
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rankings",
                to="competition.competition",
            ),
        ),
        migrations.AlterField(
            model_name="rankingsnapshotentry",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranking_entries",
                to="identity.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="rankingsnapshotentry",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ranking_entries",
                to="competition.enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exam__isnull", False)),
                fields=("exam",),
                name="unique_ranking_per_exam",
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_published", True)),
                fields=("competition", "stage", "round"),
                name="one_published_ranking_per_stage_round",
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingsnapshotentry",
            constraint=models.UniqueConstraint(
                fields=("ranking_snapshot", "candidate"),
                name="unique_candidate_per_ranking",
            ),
        ),
    ]
