# Generated by Django 5.2.6 on 2026-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "competition",
            "0010_remove_rankingsnapshot_unique_standings_per_exam_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankingsnapshotentry",
            name="exam_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Candidate's exam score used for ranking.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
