# Generated by Django 5.2.6 on 2026-03-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0011_alter_rankingsnapshotentry_exam_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rankingsnapshot",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ranking Snapshot",
                "verbose_name_plural": "Ranking Snapshots",
            },
        ),
        migrations.AddField(
            model_name="rankingsnapshot",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Whether this version should be prioritised."
            ),
        ),
    ]
