# Generated by Django 5.2.6 on 2026-03-02 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0012_alter_rankingsnapshot_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rankingsnapshot",
            name="unique_ranking_per_exam",
        ),
    ]
