# Generated by Django 5.2.6 on 2026-03-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0013_remove_rankingsnapshot_unique_ranking_per_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Active"),
                    ("active", "Active"),
                    ("eliminated", "Eliminated"),
                    ("disqualified", "Disqualified"),
                ],
                db_index=True,
                default="pending",
            ),
        ),
    ]
