# Generated by Django 5.2.6 on 2026-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0014_alter_enrollment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingsnapshotentry",
            name="time_used",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time taken to complete the exam in seconds.",
                null=True,
            ),
        ),
    ]
