# Generated by Django 5.2.6 on 2026-03-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0016_alter_enrollment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingsnapshotentry",
            name="proctoring_status",
            field=models.CharField(
                choices=[
                    ("clear", "Clear"),
                    ("suspicious", "Suspicious"),
                    ("flagged", "Flagged"),
                ],
                db_index=True,
                default="clear",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rankingsnapshotentry",
            name="violation_score",
            field=models.FloatField(
                default=0.0,
                help_text="Weighted average of suspicion scores from proctoring heartbeats.",
            ),
        ),
    ]
