# Generated by Django 5.2.6 on 2026-03-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0017_rankingsnapshotentry_proctoring_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankingsnapshotentry",
            name="proctoring_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("clear", "Clear"),
                    ("suspicious", "Suspicious"),
                    ("flagged", "Flagged"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
