# Generated by Django 5.2.6 on 2026-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0019_auto_20260314_0255"),
    ]
    operations = [
        migrations.RunSQL(
            sql=[
                "UPDATE competition_rankingsnapshotentry SET exam_score = 0 WHERE exam_score IS NULL",
            ],
            reverse_sql=[],
        ),
        migrations.AlterField(
            model_name="rankingsnapshotentry",
            name="exam_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Candidate's exam score used for ranking.",
                max_digits=5,
            ),
        ),
    ]
