# Generated by Django 5.2.6 on 2026-03-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0020_alter_rankingsnapshotentry_exam_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingsnapshotentry",
            name="attempt_status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("disqualified", "Disqualified"),
                ],
                db_index=True,
                default="present",
                max_length=20,
            ),
        ),
    ]
