# Generated by Django 5.2.6 on 2026-04-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0021_rankingsnapshotentry_attempt_status"),
        ("vmlc", "0060_candidateexamresult_is_auto_submit"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rankingsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("exam",),
                name="unique_active_snapshot_per_exam",
            ),
        ),
    ]
