# Generated by Django 5.2.6 on 2026-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0022_rankingsnapshot_unique_active_snapshot_per_exam"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leagueleaderboard",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "League Leaderboard",
                "verbose_name_plural": "League Leaderboards",
            },
        ),
        migrations.AddField(
            model_name="leagueleaderboard",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
