# Generated by Django 5.2.6 on 2026-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0023_alter_leagueleaderboard_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Competition-specific data about the candidate.",
                null=True,
            ),
        ),
    ]
