"""
This package contains all the models, views, and serializers for the API.
"""

from .models import *
from .views import *
from .serializers import *


__all__ = [
    # models
    "User",
    "CustomUserManager",
    "UserVerification",
    "EmailOTP",
    "validate_document_file",
    "validate_id_card_file",
    "validate_profile_photo",
    "Candidate",
    "CandidateManager",
    "Staff",
    "Exam",
    "Question",
    "CandidateScore",
    "CandidateAnswer",
    "LeaderboardSnapshot",
    "CandidateScoreSnapshot",
    "FeatureFlag",
    # views
    "SubmitAnswersView",
    "VerifyEmailOTPView",
    "ResendEmailOTPView",
    "RequestPasswordChangeView",
    "PasswordChangeOTPConfirmView",
    "PasswordChangeView",
    "ResendPasswordChangeOTPView",
    "CustomTokenObtainPairSerializer",
    "LoginView",
    "LogoutView",
    "CandidateListView",
    "CandidateDetailView",
    "AssignCandidateRoleView",
    "CandidateDashboardView",
    "StaffDashboardView",
    "AccountManagementView",
    "ExamListView",
    "ExamDetailView",
    "ExamResultsView",
    "ExamQuestionsView",
    "ExamHistoryView",
    "candidate_take_exam",
    "PublishLeaderboardView",
    "LoadLeaderboardView",
    "ToggleLeaderboardVisibilityView",
    "QuestionListView",
    "QuestionDetailView",
    "CandidateRegistrationView",
    "StaffRegistrationView",
    "ToggleCandidateRegistrationView",
    "ToggleStaffRegistrationView",
    "api_root",
    "CandidateScoreListView",
    "SubmitScoreView",
    "PublishScoresView",
    "StaffListView",
    "StaffDetailView",
    "AssignStaffRoleView",
    "UserVerificationStatusView",
    "UserVerificationUploadView",
    "UserVerificationDocumentView",
    "UserVerificationListView",
    "UserVerificationActionView",
    "UserProfilePhotoView",
    # serializers
    "CandidateAnswerSerializer",
    "CandidateAnswerBulkSerializer",
    "VerifyEmailOTPSerializer",
    "ResendEmailOTPSerializer",
    "RequestPasswordChangeSerializer",
    "PasswordChangeOTPConfirmSerializer",
    "PasswordChangeSerializer",
    "MinimalCandidateSerializer",
    "CandidateListSerializer",
    "CandidateDetailSerializer",
    "ExamListSerializer",
    "ExamDetailSerializer",
    "CandidateExamSerializer",
    "ExamResultSerializer",
    "QuestionListSerializer",
    "QuestionDetailSerializer",
    "CandidateQuestionSerializer",
    "CandidateRegistrationSerializer",
    "StaffRegistrationSerializer",
    "CandidateRoleSerializer",
    "StaffRoleSerializer",
    "CandidateScoreSerializer",
    "SubmitScoreSerializer",
    "CandidateExamScoreSerializer",
    "MinimalStaffSerializer",
    "StaffListSerializer",
    "StaffDetailSerializer",
    "UserSerializer",
    "MinimalUserSerializer",
    "UserVerificationStatusSerializer",
    "UserVerificationUploadView",
    "UserVerificationActionSerializer",
    "UserVerificationListSerializer",
]
