name: CI/CD pipeine

on:
  push:
    branches:
      - 'main'

jobs:
  run-tests-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Extract metadata
        id: meta
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
        
      - name: Build Docker image for tests
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: test
          tags: ${{ steps.meta.outputs.REPO_NAME }}-dev:${{ steps.meta.outputs.SHORT_SHA }}
          load: true # Load to local Docker daemon for testing
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
            
      - name: Run tests
        run: |
          docker network create test-network
          docker run -d --rm \
            -e POSTGRES_USER=testuser \
            -e POSTGRES_PASSWORD=testpassword \
            -e POSTGRES_DB=testdb \
            --network test-network \
            --name db \
            postgres:17.2-bookworm
          sleep 10
          docker run --rm \
            --network test-network \
            --entrypoint "" \
            ${{ steps.meta.outputs.REPO_NAME }}-dev:${{ steps.meta.outputs.SHORT_SHA }} \
            sh -c "python manage.py migrate --settings=config.settings.test --no-input && python manage.py test --settings=config.settings.test --noinput --keepdb --failfast"
          docker stop db
          docker network rm test-network
        timeout-minutes: 10

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Build and push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.meta.outputs.REPO_NAME }}:staging
            ghcr.io/${{ github.repository_owner }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ steps.meta.outputs.SHORT_SHA }}" > ./envfile
        
      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: vmlc-backend
          file: docker-stack.yml
          host: ${{ secrets.VPS_HOST }}
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
          